### PR TITLE
Add "keymap.yaml" support

### PR DESCRIPTION
**Pull request by kljzndx**

### CODE REVIEW

**Review by sam0x17 — APPROVED** [review]

**Review by sam0x17 — CHANGES_REQUESTED** [review]
merge conflict needs to be resolved

**Comment by kljzndx** [comment]
I don’t think the merge conflicts can be resolved. This is the least count of conflicts.

**Comment by kljzndx** [comment]
I have resolved all conflicts

**Comment by kljzndx** [comment]
please merge PR #84

**Pull request closed without merging**
