### PR TITLE
CLI options

### PR DESCRIPTION
**Pull request by albfan**
Preparing to config automatically, I added some cli options:

- `/H`: help
- `/V`: version
- `/L`: List

In list option, interesting info is shown for each joy con (Example redacted):

```
- Left Joycon , XCW11111111111, 11:22:33:44:55:66, Neon Blue, 3.89V - 63%
- Left Joycon , XCW11111111111, 11:22:33:44:55:66, Animal crossing Green, 3.89V - 63%
- Right Joycon, XCW11111111111, 11:22:33:44:55:66, HORI Red, 3.89V - 63%
- Right Joycon, XCW11111111111, 11:22:33:44:55:66, Animal crossing Blue, 3.89V - 63%
```
- Left or right
- Serial
- Body color (named if it is a know one)
- MAC

Testing several joycons the only different info is the MAC. With that info, an automatic config reading a yaml file can be created. Colors will be rendered in a `--gui` option showing a form with a treeview to select joycons and pair them visually.

This is a temptative PR to discuss implementation and see how to better setup your joycons without relay on "sync last pair connected"

### CODE REVIEW

**Comment by sam0x17** [comment]
This looks really good @albfan. I like the direction and would be happy to accept this. Let me know when it is in a state where it is ready to review.

Also note that there are quite a few issues with the default build, and the ViGEm most likely needs to be updated. I haven't run a build in over a year, so feel free to get that working in this PR so we can more easily cut a new release.

In particular, I've noticed that whenever I build this project with the release config, it still require a bunch of dll files associated with debug symbols that should only be needed in debug mode. If you happen to be knowledgeable enough to fix this, it would make it much easier for me to build new releases without having to package a bunch of random visual studio dll files with XJoy.ex.

**Comment by albfan** [comment]
I will rework that build part. If you can comment on changes that would help. I'm not that skilled in windows builds.

I prefer to update vigem in a different PR.

Then if you find it correct will add options to pair by Mac and to pair with a GUI.

Main goal is to ensure XJoy is easy to manage.

**Review by sam0x17 — APPROVED** [review]
looks good to me!

**Comment by albfan** [comment]
Great, I will rebase this and add the pair `/P` CLI option.

**Comment by albfan** [comment]
Great, I will rebase this and add the pair `/P` CLI option.

**Pull request merged**
